trigger:
  - main

variables:
- name: VCPKG_NUGET
  value: https://pkgs.dev.azure.com/natecheadle/CMakeCPPTemplate/_packaging/PIPELINE_CACHE/nuget/v3/index.json

- name: VCPKG_BINARY_SOURCES
  value: 'clear;nuget,$(VCPKG_NUGET),readwrite'

stages:
- stage: BUILD_TEST
  jobs:
  - job: WINDOWS_MSVC
    pool:
      vmImage: windows-2025
    strategy:
      matrix:
        DEBUG_X86:
          arch: x86
          cmakePreset: Windows-MSVC-x86-Debug

        RELEASE_X86:
          arch: x86
          cmakePreset: Windows-MSVC-x86-Release

        DEBUG_X64:
          arch: amd64
          cmakePreset: Windows-MSVC-x64-Debug

        RELEASE_X64:
          arch: amd64
          cmakePreset: Windows-MSVC-x64-Release

    steps:
    - task: BatchScript@1
      inputs:
        filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat'
        arguments: '-arch=$(arch)'
        modifyEnvironment: true
      displayName: "Initialize Visual Studio Environment"

    - script: |
        choco install ninja
      displayName: "Install Dependencies"

    - template: templates/build-test.yml
      parameters:
        preset: $(cmakePreset)

  - job: LINUX_GCC
    pool:
      vmImage: ubuntu-24.04

    strategy:
      matrix:
        DEBUG_14:
          gccVersion: 14
          cmakePreset: Linux-GCC-Debug

        RELEASE_14:
          gccVersion: 14
          cmakePreset: Linux-GCC-Release

    steps:
    - template: templates/install-dependencies.yml
      parameters:
        dependencies: 'ninja-build pkg-config lcov'

    - script: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-$(gccVersion) 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-$(gccVersion) 10

      displayName: "Configure Compiler Version"

    - template: templates/build-test.yml
      parameters:
        preset: $(cmakePreset)

  - job: LINUX_LLVM
    pool:
      vmImage: ubuntu-24.04

    strategy:
      matrix:
        DEBUG_18:
          llvmVersion: 18
          cmakePreset: Linux-LLVM-Debug
          coverage: false

        RELEASE_18:
          llvmVersion: 18
          cmakePreset: Linux-LLVM-Release
          coverage: false

        COVERAGE_18:
          llvmVersion: 18
          cmakePreset: Linux-LLVM-Coverage
          coverage: true

    steps:
    - template: templates/install-dependencies.yml
      parameters:
        dependencies: 'ninja-build pkg-config lcov llvm-18'

    - script: |
        sudo rm /usr/bin/clang
        sudo rm /usr/bin/clang++
        sudo ln -s /usr/bin/clang-$(llvmVersion) /usr/bin/clang
        sudo ln -s /usr/bin/clang++-$(llvmVersion) /usr/bin/clang++
        sudo ln -s /usr/bin/llvm-profdata-$(llvmVersion) /usr/bin/llvm-profdata
        sudo ln -s /usr/bin/llvm-cov-$(llvmVersion) /usr/bin/llvm-cov
      displayName: "Configure Compiler Version"

    - template: templates/build-test.yml
      parameters:
        preset: $(cmakePreset)
        build_coverage: $(coverage)